# Server settings
server:
    port: 80
    address: 0.0.0.0
# SPRING PROFILES
spring:
    devtools:
        restart:
            enabled: true
            exclude: templates/**
    thymeleaf:
        prefix:
            classpath: /templates/
        mode: LEGACYHTML5
        suffix: .html
        encoding: UTF-8
        content-type: text/html
        cache: false
    datasource:
            driverClass: com.mysql.jdbc.Driver
            url: jdbc:mysql://127.0.0.1:3306/travel?useUnicode=true&characterEncoding=utf-8
            username: root
            password: 123456
mybatis:
    configuration:
            mapUnderscoreToCamelCase: true
pagehelper:
    helperDialect: mysql
    #RowBounds第一个参数offset当做页码，默认为false
    offsetAsPageNum: true
    #使用RowBounds分页会进行count查询，默认为false
    rowBoundsWithCount: true
    #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
    reasonable: false
    #支持通过Mapper接口参数来传递分页参数
    supportMethodsArguments: true
    #设置为true时，如果pageSize=0遍历全部结果，相当于没有分页
    pageSizeZero: true
    #映射参数
    params: count=countSql
logging:
    level:
      #打印SQL信息
      #com.hehe.mapper: debug
      com.cn.travel: debug
